sql -s ${ORACLE_USERNAME_ADMIN}/${ORACLE_PASSWORD_ADMIN}@${ORACLE_IP}:${ORACLE_PORT}/${ORACLE_PDB} <<EOF
CREATE USER ${ORACLE_USERNAME} IDENTIFIED BY ${ORACLE_PASSWORD} DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON users;
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO ${ORACLE_USERNAME};
EXIT
EOF

sql -s ${ORACLE_USERNAME}/${ORACLE_PASSWORD}@${ORACLE_IP}:${ORACLE_PORT}/${ORACLE_PDB} @./src/main/resources/db.sql